import * as dotenv from 'dotenv';

const PROD_MODE = (process.env['PROD_MODE'] as any) || 'local';

switch (PROD_MODE) {
	case 'local':
		dotenv.config({ path: './.env' });
		break;
}

const API_INFO = {
	URI: process.env['API_INFO_URI'],
	VERSION: process.env['API_INFO_VERSION'],
};

const WEB_INFO = {
	URI: process.env['WEB_INFO_URI'],
};

const SESSION_SECRET = process.env['SESSION_SECRET'];

const SOCIAL_CONFIG = {
	CLIENT_ID_NAVER: process.env['SOCIAL_CONFIG_CLIENT_ID_NAVER'],
	CLIENT_SECRET_NAVER: process.env['SOCIAL_CONFIG_CLIENT_SECRET_NAVER'],
	CALLBACK_URL_NAVER: API_INFO.URI + process.env['SOCIAL_CONFIG_CALLBACK_URL_NAVER'],

	CLIENT_ID_FACEBOOK: process.env['SOCIAL_CONFIG_CLIENT_ID_FACEBOOK'],
	CLIENT_SECRET_FACEBOOK: process.env['SOCIAL_CONFIG_CLIENT_SECRET_FACEBOOK'],
	CALLBACK_URL_FACEBOOK: API_INFO.URI + process.env['SOCIAL_CONFIG_CALLBACK_URL_FACEBOOK'],

	CLIENT_ID_KAKAO: process.env['SOCIAL_CONFIG_CLIENT_ID_KAKAO'],
	CALLBACK_URL_KAKAO: API_INFO.URI + process.env['SOCIAL_CONFIG_CALLBACK_URL_KAKAO'],

	CLIENT_ID_GOOGLE: process.env['SOCIAL_CONFIG_CLIENT_ID_GOOGLE'],
	CLIENT_SECRET_GOOGLE: process.env['SOCIAL_CONFIG_CLIENT_SECRET_GOOGLE'],
	CALLBACK_URL_GOOGLE: API_INFO.URI + process.env['SOCIAL_CONFIG_CALLBACK_URL_GOOGLE'],

	SUC_LOGIN_URL: WEB_INFO.URI + process.env['SOCIAL_CONFIG_SUC_LOGIN_URL'],
	FAIL_LOGIN_URL: WEB_INFO.URI + process.env['SOCIAL_CONFIG_FAIL_LOGIN_URL'],
};

export const Constants = { PROD_MODE, API_INFO, WEB_INFO, SOCIAL_CONFIG, SESSION_SECRET };
